# search_profiles/registry.py
# AUTO-GENERATED by agent_loop.py — do not edit manually.
# Updated whenever a new best experiment is kept.
# Cross-reference with experiments/log.jsonl by exp_id.

PROFILES = {
    "high_recall": {
        "module": "search_profiles.high_recall",
        "recall": 0.681818,
        "latency_ms": 24.255082942545414,
        "cost_usd": 0.000789,
        "description": "maximize recall — best for full search pages",
        "objective": "recall",
        "use_when": "accuracy matters most — full search, recommendation",
    },
    "low_latency": {
        "module": "search_profiles.low_latency",
        "recall": 0.636364,
        "latency_ms": 23.40341592207551,
        "cost_usd": 0.001152,
        "description": "minimize latency — fastest response",
        "objective": "latency",
        "use_when": "speed matters most — autocomplete, typeahead",
    },
    "balanced": {
        "module": "search_profiles.balanced",
        "recall": 0.681818,
        "latency_ms": 22.205957677215338,
        "cost_usd": 0.001501,
        "description": "best recall/latency tradeoff",
        "objective": "pareto",
        "use_when": "default — general search, no specific SLA",
    },
    "low_cost": {
        "module": "search_profiles.low_cost",
        "recall": 0.636364,
        "latency_ms": 23.173917084932327,
        "cost_usd": 0.001173,
        "description": "minimize LLM cost — simplest implementation",
        "objective": "cost",
        "use_when": "high volume, cost-sensitive workloads",
    },
}

# Fallback when constraint is unknown or profile file missing
DEFAULT_PROFILE = 'balanced'
