# search_profiles/registry.py
# AUTO-GENERATED by agent_loop.py — do not edit manually.
# Updated whenever a new best experiment is kept.
# Cross-reference with experiments/log.jsonl by exp_id.

PROFILES = {
    "high_recall": {
        "module": "search_profiles.high_recall",
        "recall": 0.509804,
        "latency_ms": 10.181721519021426,
        "cost_usd": 0.0,
        "description": "maximize recall — best for full search pages",
        "objective": "recall",
        "use_when": "accuracy matters most — full search, recommendation",
    },
    "low_latency": {
        "module": "search_profiles.low_latency",
        "recall": 0.196078,
        "latency_ms": 6.890647551592658,
        "cost_usd": 0.000574,
        "description": "minimize latency — fastest response",
        "objective": "latency",
        "use_when": "speed matters most — autocomplete, typeahead",
    },
    "balanced": {
        "module": "search_profiles.balanced",
        "recall": 0.509804,
        "latency_ms": 13.680154202031154,
        "cost_usd": 0.0,
        "description": "best recall/latency tradeoff",
        "objective": "pareto",
        "use_when": "default — general search, no specific SLA",
    },
}

# Fallback when constraint is unknown or profile file missing
DEFAULT_PROFILE = "balanced"
